/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Location

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param status 
 * @param species 
 * @param gender 
 * @param origin 
 * @param type 
 * @param location 
 * @param image 
 * @param url 
 * @param created 
 * @param episode 
 */
@Serializable

data class Character (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "species") @Required val species: kotlin.String,

    @SerialName(value = "gender") @Required val gender: kotlin.String,

    @SerialName(value = "origin") @Required val origin: Location,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "location") val location: Location? = null,

    @SerialName(value = "image") val image: kotlin.String? = null,

    @SerialName(value = "url") val url: kotlin.String? = null,

    @SerialName(value = "created") val created: kotlin.String? = null,

    @SerialName(value = "episode") val episode: kotlin.collections.List<kotlin.String>? = null

) {


}

