/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Character
import org.openapitools.client.models.Info

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param info 
 * @param results 
 */
@Serializable

data class CharactersList (

    @SerialName(value = "info") @Required val info: Info,

    @SerialName(value = "results") val results: kotlin.collections.List<Character>? = null

) {


}

