//
// DistributionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DistributionsAPI {

    /**
     GET /distributions
     
     - returns: DistributionsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getDistributions() async throws -> DistributionsResponse {
        return try await getDistributionsWithRequestBuilder().execute().body
    }

    /**
     GET /distributions
     - GET /distributions
     - Distributions of MMR data by bracket and country
     - returns: RequestBuilder<DistributionsResponse> 
     */
    open class func getDistributionsWithRequestBuilder() -> RequestBuilder<DistributionsResponse> {
        let localVariablePath = "/distributions"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DistributionsResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
