//
// ExplorerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ExplorerAPI {

    /**
     GET /explorer
     
     - parameter sql: (query) The PostgreSQL query as percent-encoded string. (optional)
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getExplorer(sql: String? = nil) async throws -> AnyCodable {
        return try await getExplorerWithRequestBuilder(sql: sql).execute().body
    }

    /**
     GET /explorer
     - GET /explorer
     - Submit arbitrary SQL queries to the database
     - parameter sql: (query) The PostgreSQL query as percent-encoded string. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func getExplorerWithRequestBuilder(sql: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/explorer"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "sql": (wrappedValue: sql?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
