//
// FindMatchesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class FindMatchesAPI {

    /**
     GET /
     
     - parameter teamA: (query) Hero IDs on first team (array) (optional)
     - parameter teamB: (query) Hero IDs on second team (array) (optional)
     - returns: [AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getFindMatches(teamA: [Int]? = nil, teamB: [Int]? = nil) async throws -> [AnyCodable] {
        return try await getFindMatchesWithRequestBuilder(teamA: teamA, teamB: teamB).execute().body
    }

    /**
     GET /
     - GET /findMatches
     - Finds recent matches by heroes played
     - parameter teamA: (query) Hero IDs on first team (array) (optional)
     - parameter teamB: (query) Hero IDs on second team (array) (optional)
     - returns: RequestBuilder<[AnyCodable]> 
     */
    open class func getFindMatchesWithRequestBuilder(teamA: [Int]? = nil, teamB: [Int]? = nil) -> RequestBuilder<[AnyCodable]> {
        let localVariablePath = "/findMatches"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "teamA": (wrappedValue: teamA?.encodeToJSON(), isExplode: false),
            "teamB": (wrappedValue: teamB?.encodeToJSON(), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AnyCodable]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
