//
// HeroStatsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class HeroStatsAPI {

    /**
     GET /heroStats
     
     - returns: [HeroStatsResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHeroStats() async throws -> [HeroStatsResponse] {
        return try await getHeroStatsWithRequestBuilder().execute().body
    }

    /**
     GET /heroStats
     - GET /heroStats
     - Get stats about hero performance in recent matches
     - returns: RequestBuilder<[HeroStatsResponse]> 
     */
    open class func getHeroStatsWithRequestBuilder() -> RequestBuilder<[HeroStatsResponse]> {
        let localVariablePath = "/heroStats"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[HeroStatsResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
