//
// LeaguesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class LeaguesAPI {

    /**
     GET /leagues
     
     - returns: [LeagueObjectResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getLeagues() async throws -> [LeagueObjectResponse] {
        return try await getLeaguesWithRequestBuilder().execute().body
    }

    /**
     GET /leagues
     - GET /leagues
     - Get league data
     - returns: RequestBuilder<[LeagueObjectResponse]> 
     */
    open class func getLeaguesWithRequestBuilder() -> RequestBuilder<[LeagueObjectResponse]> {
        let localVariablePath = "/leagues"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[LeagueObjectResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /leagues/{league_id}
     
     - parameter leagueId: (path) League ID 
     - returns: [LeagueObjectResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getLeaguesByLeagueId(leagueId: Int) async throws -> [LeagueObjectResponse] {
        return try await getLeaguesByLeagueIdWithRequestBuilder(leagueId: leagueId).execute().body
    }

    /**
     GET /leagues/{league_id}
     - GET /leagues/{league_id}
     - Get data for a league
     - parameter leagueId: (path) League ID 
     - returns: RequestBuilder<[LeagueObjectResponse]> 
     */
    open class func getLeaguesByLeagueIdWithRequestBuilder(leagueId: Int) -> RequestBuilder<[LeagueObjectResponse]> {
        var localVariablePath = "/leagues/{league_id}"
        let leagueIdPreEscape = "\(APIHelper.mapValueToPathItem(leagueId))"
        let leagueIdPostEscape = leagueIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{league_id}", with: leagueIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[LeagueObjectResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /leagues/{league_id}/matches
     
     - parameter leagueId: (path) League ID 
     - returns: MatchObjectResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getLeaguesByLeagueIdSelectMatches(leagueId: Int) async throws -> MatchObjectResponse {
        return try await getLeaguesByLeagueIdSelectMatchesWithRequestBuilder(leagueId: leagueId).execute().body
    }

    /**
     GET /leagues/{league_id}/matches
     - GET /leagues/{league_id}/matches
     - Get matches for a team
     - parameter leagueId: (path) League ID 
     - returns: RequestBuilder<MatchObjectResponse> 
     */
    open class func getLeaguesByLeagueIdSelectMatchesWithRequestBuilder(leagueId: Int) -> RequestBuilder<MatchObjectResponse> {
        var localVariablePath = "/leagues/{league_id}/matches"
        let leagueIdPreEscape = "\(APIHelper.mapValueToPathItem(leagueId))"
        let leagueIdPostEscape = leagueIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{league_id}", with: leagueIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MatchObjectResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /leagues/{league_id}/teams
     
     - parameter leagueId: (path) League ID 
     - returns: TeamObjectResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getLeaguesByLeagueIdSelectTeams(leagueId: Int) async throws -> TeamObjectResponse {
        return try await getLeaguesByLeagueIdSelectTeamsWithRequestBuilder(leagueId: leagueId).execute().body
    }

    /**
     GET /leagues/{league_id}/teams
     - GET /leagues/{league_id}/teams
     - Get teams for a league
     - parameter leagueId: (path) League ID 
     - returns: RequestBuilder<TeamObjectResponse> 
     */
    open class func getLeaguesByLeagueIdSelectTeamsWithRequestBuilder(leagueId: Int) -> RequestBuilder<TeamObjectResponse> {
        var localVariablePath = "/leagues/{league_id}/teams"
        let leagueIdPreEscape = "\(APIHelper.mapValueToPathItem(leagueId))"
        let leagueIdPostEscape = leagueIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{league_id}", with: leagueIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TeamObjectResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
