//
// MatchesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MatchesAPI {

    /**
     GET /matches/{match_id}
     
     - parameter matchId: (path)  
     - returns: MatchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMatchesByMatchId(matchId: Int) async throws -> MatchResponse {
        return try await getMatchesByMatchIdWithRequestBuilder(matchId: matchId).execute().body
    }

    /**
     GET /matches/{match_id}
     - GET /matches/{match_id}
     - Match data
     - parameter matchId: (path)  
     - returns: RequestBuilder<MatchResponse> 
     */
    open class func getMatchesByMatchIdWithRequestBuilder(matchId: Int) -> RequestBuilder<MatchResponse> {
        var localVariablePath = "/matches/{match_id}"
        let matchIdPreEscape = "\(APIHelper.mapValueToPathItem(matchId))"
        let matchIdPostEscape = matchIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{match_id}", with: matchIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MatchResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
