//
// ParsedMatchesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ParsedMatchesAPI {

    /**
     GET /parsedMatches
     
     - parameter lessThanMatchId: (query) Get matches with a match ID lower than this value (optional)
     - returns: [ParsedMatchesResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getParsedMatches(lessThanMatchId: Int? = nil) async throws -> [ParsedMatchesResponse] {
        return try await getParsedMatchesWithRequestBuilder(lessThanMatchId: lessThanMatchId).execute().body
    }

    /**
     GET /parsedMatches
     - GET /parsedMatches
     - Get list of parsed match IDs
     - parameter lessThanMatchId: (query) Get matches with a match ID lower than this value (optional)
     - returns: RequestBuilder<[ParsedMatchesResponse]> 
     */
    open class func getParsedMatchesWithRequestBuilder(lessThanMatchId: Int? = nil) -> RequestBuilder<[ParsedMatchesResponse]> {
        let localVariablePath = "/parsedMatches"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "less_than_match_id": (wrappedValue: lessThanMatchId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ParsedMatchesResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
