//
// ProPlayersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ProPlayersAPI {

    /**
     GET /proPlayers
     
     - returns: [PlayerObjectResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getProPlayers() async throws -> [PlayerObjectResponse] {
        return try await getProPlayersWithRequestBuilder().execute().body
    }

    /**
     GET /proPlayers
     - GET /proPlayers
     - Get list of pro players
     - returns: RequestBuilder<[PlayerObjectResponse]> 
     */
    open class func getProPlayersWithRequestBuilder() -> RequestBuilder<[PlayerObjectResponse]> {
        let localVariablePath = "/proPlayers"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PlayerObjectResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
