//
// HeroItemPopularityResponseMidGameItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Items bought between 10 and 25 min of the game, with cost at least 2000 */
public struct HeroItemPopularityResponseMidGameItems: Codable, JSONEncodable, Hashable {

    /** Number of item bought */
    public var item: Int?

    public init(item: Int? = nil) {
        self.item = item
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case item
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(item, forKey: .item)
    }
}

