//
// HeroDurationsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HeroDurationsResponse: Codable, JSONEncodable, Hashable {

    /** Lower bound of number of seconds the match lasted */
    public var durationBin: String?
    /** Number of games played */
    public var gamesPlayed: Int?
    /** Number of wins */
    public var wins: Int?

    public init(durationBin: String? = nil, gamesPlayed: Int? = nil, wins: Int? = nil) {
        self.durationBin = durationBin
        self.gamesPlayed = gamesPlayed
        self.wins = wins
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case durationBin = "duration_bin"
        case gamesPlayed = "games_played"
        case wins
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(durationBin, forKey: .durationBin)
        try container.encodeIfPresent(gamesPlayed, forKey: .gamesPlayed)
        try container.encodeIfPresent(wins, forKey: .wins)
    }
}

