//
// MatchResponsePicksBansInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MatchResponsePicksBansInner: Codable, JSONEncodable, Hashable {

    /** Boolean indicating whether the choice is a pick or a ban */
    public var isPick: Bool?
    /** The ID value of the hero played */
    public var heroId: Int?
    /** The team that picked or banned the hero */
    public var team: Int?
    /** The order of the pick or ban */
    public var order: Int?

    public init(isPick: Bool? = nil, heroId: Int? = nil, team: Int? = nil, order: Int? = nil) {
        self.isPick = isPick
        self.heroId = heroId
        self.team = team
        self.order = order
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isPick = "is_pick"
        case heroId = "hero_id"
        case team
        case order
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isPick, forKey: .isPick)
        try container.encodeIfPresent(heroId, forKey: .heroId)
        try container.encodeIfPresent(team, forKey: .team)
        try container.encodeIfPresent(order, forKey: .order)
    }
}

