//
// MatchResponsePlayersInnerConnectionLogInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MatchResponsePlayersInnerConnectionLogInner: Codable, JSONEncodable, Hashable {

    /** Game time in seconds the event ocurred */
    public var time: Int?
    /** Event that occurred */
    public var event: String?
    /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
    public var playerSlot: Int?

    public init(time: Int? = nil, event: String? = nil, playerSlot: Int? = nil) {
        self.time = time
        self.event = event
        self.playerSlot = playerSlot
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case event
        case playerSlot = "player_slot"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encodeIfPresent(playerSlot, forKey: .playerSlot)
    }
}

