//
// MatchResponsePlayersInnerRunesLogInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MatchResponsePlayersInnerRunesLogInner: Codable, JSONEncodable, Hashable {

    /** Time in seconds rune picked up */
    public var time: Int?
    /** key */
    public var key: Int?

    public init(time: Int? = nil, key: Int? = nil) {
        self.time = time
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(key, forKey: .key)
    }
}

