//
// MatchResponsePlayersInnerBuybackLogInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MatchResponsePlayersInnerBuybackLogInner: Codable, JSONEncodable, Hashable {

    /** Time in seconds the buyback occurred */
    public var time: Int?
    /** slot */
    public var slot: Int?
    /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
    public var playerSlot: Int?

    public init(time: Int? = nil, slot: Int? = nil, playerSlot: Int? = nil) {
        self.time = time
        self.slot = slot
        self.playerSlot = playerSlot
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case slot
        case playerSlot = "player_slot"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(slot, forKey: .slot)
        try container.encodeIfPresent(playerSlot, forKey: .playerSlot)
    }
}

