//
// MatchResponsePlayersInnerNeutralItemHistoryInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MatchResponsePlayersInnerNeutralItemHistoryInner: Codable, JSONEncodable, Hashable {

    /** Time in seconds at which the item was crafted */
    public var time: Int?
    /** Neutral item name */
    public var itemNeutral: String?
    /** Neutral enhancement name */
    public var itemNeutralEnhancement: String?

    public init(time: Int? = nil, itemNeutral: String? = nil, itemNeutralEnhancement: String? = nil) {
        self.time = time
        self.itemNeutral = itemNeutral
        self.itemNeutralEnhancement = itemNeutralEnhancement
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case itemNeutral = "item_neutral"
        case itemNeutralEnhancement = "item_neutral_enhancement"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(itemNeutral, forKey: .itemNeutral)
        try container.encodeIfPresent(itemNeutralEnhancement, forKey: .itemNeutralEnhancement)
    }
}

