//
// MatchResponsePlayersInnerPurchaseLogInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MatchResponsePlayersInnerPurchaseLogInner: Codable, JSONEncodable, Hashable {

    /** Time in seconds the item was bought */
    public var time: Int?
    /** String item ID */
    public var key: String?
    /** Integer amount of charges */
    public var charges: Int?

    public init(time: Int? = nil, key: String? = nil, charges: Int? = nil) {
        self.time = time
        self.key = key
        self.charges = charges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case key
        case charges
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(charges, forKey: .charges)
    }
}

