//
// MatchResponseChatInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MatchResponseChatInner: Codable, JSONEncodable, Hashable {

    /** Time in seconds at which the message was said */
    public var time: Int?
    /** Name of the player who sent the message */
    public var unit: String?
    /** The message the player sent */
    public var key: String?
    /** slot */
    public var slot: Int?
    /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
    public var playerSlot: Int?

    public init(time: Int? = nil, unit: String? = nil, key: String? = nil, slot: Int? = nil, playerSlot: Int? = nil) {
        self.time = time
        self.unit = unit
        self.key = key
        self.slot = slot
        self.playerSlot = playerSlot
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case unit
        case key
        case slot
        case playerSlot = "player_slot"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(unit, forKey: .unit)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(slot, forKey: .slot)
        try container.encodeIfPresent(playerSlot, forKey: .playerSlot)
    }
}

