//
// MetadataResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MetadataResponse: Codable, JSONEncodable, Hashable {

    /** banner */
    public var banner: AnyCodable?

    public init(banner: AnyCodable? = nil) {
        self.banner = banner
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case banner
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(banner, forKey: .banner)
    }
}

