//
// PlayerWardMapResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayerWardMapResponse: Codable, JSONEncodable, Hashable {

    /** obs */
    public var obs: AnyCodable?
    /** sen */
    public var sen: AnyCodable?

    public init(obs: AnyCodable? = nil, sen: AnyCodable? = nil) {
        self.obs = obs
        self.sen = sen
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case obs
        case sen
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(obs, forKey: .obs)
        try container.encodeIfPresent(sen, forKey: .sen)
    }
}

