//
// PlayerWordCloudResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayerWordCloudResponse: Codable, JSONEncodable, Hashable {

    /** my_word_counts */
    public var myWordCounts: AnyCodable?
    /** all_word_counts */
    public var allWordCounts: AnyCodable?

    public init(myWordCounts: AnyCodable? = nil, allWordCounts: AnyCodable? = nil) {
        self.myWordCounts = myWordCounts
        self.allWordCounts = allWordCounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case myWordCounts = "my_word_counts"
        case allWordCounts = "all_word_counts"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(myWordCounts, forKey: .myWordCounts)
        try container.encodeIfPresent(allWordCounts, forKey: .allWordCounts)
    }
}

