//
// RankingsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RankingsResponse: Codable, JSONEncodable, Hashable {

    /** The ID value of the hero played */
    public var heroId: Int?
    /** rankings */
    public var rankings: [RankingsResponseRankingsInner]?

    public init(heroId: Int? = nil, rankings: [RankingsResponseRankingsInner]? = nil) {
        self.heroId = heroId
        self.rankings = rankings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case heroId = "hero_id"
        case rankings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(heroId, forKey: .heroId)
        try container.encodeIfPresent(rankings, forKey: .rankings)
    }
}

