//
// ScenarioItemTimingsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScenarioItemTimingsResponse: Codable, JSONEncodable, Hashable {

    /** The ID value of the hero played */
    public var heroId: Int?
    /** Purchased item */
    public var item: String?
    /** Ingame time in seconds before the item was purchased */
    public var time: Int?
    /** The number of games where the hero bought this item before this time */
    public var games: String?
    /** The number of games won where the hero bought this item before this time */
    public var wins: String?

    public init(heroId: Int? = nil, item: String? = nil, time: Int? = nil, games: String? = nil, wins: String? = nil) {
        self.heroId = heroId
        self.item = item
        self.time = time
        self.games = games
        self.wins = wins
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case heroId = "hero_id"
        case item
        case time
        case games
        case wins
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(heroId, forKey: .heroId)
        try container.encodeIfPresent(item, forKey: .item)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(games, forKey: .games)
        try container.encodeIfPresent(wins, forKey: .wins)
    }
}

