//
// SchemaResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SchemaResponse: Codable, JSONEncodable, Hashable {

    /** table_name */
    public var tableName: String?
    /** column_name */
    public var columnName: String?
    /** data_type */
    public var dataType: String?

    public init(tableName: String? = nil, columnName: String? = nil, dataType: String? = nil) {
        self.tableName = tableName
        self.columnName = columnName
        self.dataType = dataType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tableName = "table_name"
        case columnName = "column_name"
        case dataType = "data_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tableName, forKey: .tableName)
        try container.encodeIfPresent(columnName, forKey: .columnName)
        try container.encodeIfPresent(dataType, forKey: .dataType)
    }
}

