//
// SearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResponse: Codable, JSONEncodable, Hashable {

    /** The player account ID */
    public var accountId: Int?
    /** avatarfull */
    public var avatarfull: String?
    /** Player's Steam name */
    public var personaname: String?
    /** last_match_time. May not be present or null. */
    public var lastMatchTime: String?
    /** similarity */
    public var similarity: Double?

    public init(accountId: Int? = nil, avatarfull: String? = nil, personaname: String? = nil, lastMatchTime: String? = nil, similarity: Double? = nil) {
        self.accountId = accountId
        self.avatarfull = avatarfull
        self.personaname = personaname
        self.lastMatchTime = lastMatchTime
        self.similarity = similarity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case avatarfull
        case personaname
        case lastMatchTime = "last_match_time"
        case similarity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(avatarfull, forKey: .avatarfull)
        try container.encodeIfPresent(personaname, forKey: .personaname)
        try container.encodeIfPresent(lastMatchTime, forKey: .lastMatchTime)
        try container.encodeIfPresent(similarity, forKey: .similarity)
    }
}

