//
// TeamObjectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TeamObjectResponse: Codable, JSONEncodable, Hashable {

    /** Team's identifier */
    public var teamId: Int?
    /** The Elo rating of the team */
    public var rating: Double?
    /** The number of games won by this team */
    public var wins: Int?
    /** The number of losses by this team */
    public var losses: Int?
    /** The Unix timestamp of the last match played by this team */
    public var lastMatchTime: Int?
    /** Team name */
    public var name: String?
    /** The team tag/abbreviation */
    public var tag: String?

    public init(teamId: Int? = nil, rating: Double? = nil, wins: Int? = nil, losses: Int? = nil, lastMatchTime: Int? = nil, name: String? = nil, tag: String? = nil) {
        self.teamId = teamId
        self.rating = rating
        self.wins = wins
        self.losses = losses
        self.lastMatchTime = lastMatchTime
        self.name = name
        self.tag = tag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case teamId = "team_id"
        case rating
        case wins
        case losses
        case lastMatchTime = "last_match_time"
        case name
        case tag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(teamId, forKey: .teamId)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(wins, forKey: .wins)
        try container.encodeIfPresent(losses, forKey: .losses)
        try container.encodeIfPresent(lastMatchTime, forKey: .lastMatchTime)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(tag, forKey: .tag)
    }
}

