/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.CharactersApi
import org.openapitools.client.models.Character
import org.openapitools.client.models.CharactersList

class CharactersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CharactersApi
        //val apiInstance = CharactersApi()

        // to test getAllCharacters
        should("test getAllCharacters") {
            // uncomment below to test getAllCharacters
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val result : CharactersList = apiInstance.getAllCharacters(page)
            //result shouldBe ("TODO")
        }

        // to test getCharacterById
        should("test getCharacterById") {
            // uncomment below to test getCharacterById
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val result : Character = apiInstance.getCharacterById(id)
            //result shouldBe ("TODO")
        }

    }
}
