//
// HeroesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class HeroesAPI {

    /**
     GET /heroes
     
     - returns: [HeroObjectResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHeroes() async throws -> [HeroObjectResponse] {
        return try await getHeroesWithRequestBuilder().execute().body
    }

    /**
     GET /heroes
     - GET /heroes
     - Get hero data
     - returns: RequestBuilder<[HeroObjectResponse]> 
     */
    open class func getHeroesWithRequestBuilder() -> RequestBuilder<[HeroObjectResponse]> {
        let localVariablePath = "/heroes"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[HeroObjectResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /heroes/{hero_id}/durations
     
     - parameter heroId: (path) Hero ID 
     - returns: [HeroDurationsResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHeroesByHeroIdSelectDurations(heroId: Int) async throws -> [HeroDurationsResponse] {
        return try await getHeroesByHeroIdSelectDurationsWithRequestBuilder(heroId: heroId).execute().body
    }

    /**
     GET /heroes/{hero_id}/durations
     - GET /heroes/{hero_id}/durations
     - Get hero performance over a range of match durations
     - parameter heroId: (path) Hero ID 
     - returns: RequestBuilder<[HeroDurationsResponse]> 
     */
    open class func getHeroesByHeroIdSelectDurationsWithRequestBuilder(heroId: Int) -> RequestBuilder<[HeroDurationsResponse]> {
        var localVariablePath = "/heroes/{hero_id}/durations"
        let heroIdPreEscape = "\(APIHelper.mapValueToPathItem(heroId))"
        let heroIdPostEscape = heroIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{hero_id}", with: heroIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[HeroDurationsResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /heroes/{hero_id}/itemPopularity
     
     - parameter heroId: (path) Hero ID 
     - returns: HeroItemPopularityResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHeroesByHeroIdSelectItemPopularity(heroId: Int) async throws -> HeroItemPopularityResponse {
        return try await getHeroesByHeroIdSelectItemPopularityWithRequestBuilder(heroId: heroId).execute().body
    }

    /**
     GET /heroes/{hero_id}/itemPopularity
     - GET /heroes/{hero_id}/itemPopularity
     - Get item popularity of hero categoried by start, early, mid and late game, analyzed from professional games
     - parameter heroId: (path) Hero ID 
     - returns: RequestBuilder<HeroItemPopularityResponse> 
     */
    open class func getHeroesByHeroIdSelectItemPopularityWithRequestBuilder(heroId: Int) -> RequestBuilder<HeroItemPopularityResponse> {
        var localVariablePath = "/heroes/{hero_id}/itemPopularity"
        let heroIdPreEscape = "\(APIHelper.mapValueToPathItem(heroId))"
        let heroIdPostEscape = heroIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{hero_id}", with: heroIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HeroItemPopularityResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /heroes/{hero_id}/matches
     
     - parameter heroId: (path) Hero ID 
     - returns: [MatchObjectResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHeroesByHeroIdSelectMatches(heroId: Int) async throws -> [MatchObjectResponse] {
        return try await getHeroesByHeroIdSelectMatchesWithRequestBuilder(heroId: heroId).execute().body
    }

    /**
     GET /heroes/{hero_id}/matches
     - GET /heroes/{hero_id}/matches
     - Get recent matches with a hero
     - parameter heroId: (path) Hero ID 
     - returns: RequestBuilder<[MatchObjectResponse]> 
     */
    open class func getHeroesByHeroIdSelectMatchesWithRequestBuilder(heroId: Int) -> RequestBuilder<[MatchObjectResponse]> {
        var localVariablePath = "/heroes/{hero_id}/matches"
        let heroIdPreEscape = "\(APIHelper.mapValueToPathItem(heroId))"
        let heroIdPostEscape = heroIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{hero_id}", with: heroIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[MatchObjectResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /heroes/{hero_id}/matchups
     
     - parameter heroId: (path) Hero ID 
     - returns: [HeroMatchupsResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHeroesByHeroIdSelectMatchups(heroId: Int) async throws -> [HeroMatchupsResponse] {
        return try await getHeroesByHeroIdSelectMatchupsWithRequestBuilder(heroId: heroId).execute().body
    }

    /**
     GET /heroes/{hero_id}/matchups
     - GET /heroes/{hero_id}/matchups
     - Get results against other heroes for a hero
     - parameter heroId: (path) Hero ID 
     - returns: RequestBuilder<[HeroMatchupsResponse]> 
     */
    open class func getHeroesByHeroIdSelectMatchupsWithRequestBuilder(heroId: Int) -> RequestBuilder<[HeroMatchupsResponse]> {
        var localVariablePath = "/heroes/{hero_id}/matchups"
        let heroIdPreEscape = "\(APIHelper.mapValueToPathItem(heroId))"
        let heroIdPostEscape = heroIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{hero_id}", with: heroIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[HeroMatchupsResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /heroes/{hero_id}/players
     
     - parameter heroId: (path) Hero ID 
     - returns: [[PlayerObjectResponse]]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHeroesByHeroIdSelectPlayers(heroId: Int) async throws -> [[PlayerObjectResponse]] {
        return try await getHeroesByHeroIdSelectPlayersWithRequestBuilder(heroId: heroId).execute().body
    }

    /**
     GET /heroes/{hero_id}/players
     - GET /heroes/{hero_id}/players
     - Get players who have played this hero
     - parameter heroId: (path) Hero ID 
     - returns: RequestBuilder<[[PlayerObjectResponse]]> 
     */
    open class func getHeroesByHeroIdSelectPlayersWithRequestBuilder(heroId: Int) -> RequestBuilder<[[PlayerObjectResponse]]> {
        var localVariablePath = "/heroes/{hero_id}/players"
        let heroIdPreEscape = "\(APIHelper.mapValueToPathItem(heroId))"
        let heroIdPostEscape = heroIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{hero_id}", with: heroIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[[PlayerObjectResponse]]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
