//
// RankingsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RankingsAPI {

    /**
     GET /rankings
     
     - parameter heroId: (query) Hero ID 
     - returns: RankingsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRankings(heroId: String) async throws -> RankingsResponse {
        return try await getRankingsWithRequestBuilder(heroId: heroId).execute().body
    }

    /**
     GET /rankings
     - GET /rankings
     - Top players by hero
     - parameter heroId: (query) Hero ID 
     - returns: RequestBuilder<RankingsResponse> 
     */
    open class func getRankingsWithRequestBuilder(heroId: String) -> RequestBuilder<RankingsResponse> {
        let localVariablePath = "/rankings"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "hero_id": (wrappedValue: heroId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RankingsResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
