//
// ScenariosAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ScenariosAPI {

    /**
     GET /scenarios/itemTimings
     
     - parameter item: (query) Filter by item name e.g. \&quot;spirit_vessel\&quot; (optional)
     - parameter heroId: (query) Hero ID (optional)
     - returns: [ScenarioItemTimingsResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getScenariosItemTimings(item: String? = nil, heroId: Int? = nil) async throws -> [ScenarioItemTimingsResponse] {
        return try await getScenariosItemTimingsWithRequestBuilder(item: item, heroId: heroId).execute().body
    }

    /**
     GET /scenarios/itemTimings
     - GET /scenarios/itemTimings
     - Win rates for certain item timings on a hero for items that cost at least 1400 gold
     - parameter item: (query) Filter by item name e.g. \&quot;spirit_vessel\&quot; (optional)
     - parameter heroId: (query) Hero ID (optional)
     - returns: RequestBuilder<[ScenarioItemTimingsResponse]> 
     */
    open class func getScenariosItemTimingsWithRequestBuilder(item: String? = nil, heroId: Int? = nil) -> RequestBuilder<[ScenarioItemTimingsResponse]> {
        let localVariablePath = "/scenarios/itemTimings"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "item": (wrappedValue: item?.encodeToJSON(), isExplode: true),
            "hero_id": (wrappedValue: heroId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ScenarioItemTimingsResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /scenarios/laneRoles
     
     - parameter laneRole: (query) Filter by lane role 1-4 (Safe, Mid, Off, Jungle) (optional)
     - parameter heroId: (query) Hero ID (optional)
     - returns: [ScenarioLaneRolesResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getScenariosLaneRoles(laneRole: String? = nil, heroId: Int? = nil) async throws -> [ScenarioLaneRolesResponse] {
        return try await getScenariosLaneRolesWithRequestBuilder(laneRole: laneRole, heroId: heroId).execute().body
    }

    /**
     GET /scenarios/laneRoles
     - GET /scenarios/laneRoles
     - Win rates for heroes in certain lane roles
     - parameter laneRole: (query) Filter by lane role 1-4 (Safe, Mid, Off, Jungle) (optional)
     - parameter heroId: (query) Hero ID (optional)
     - returns: RequestBuilder<[ScenarioLaneRolesResponse]> 
     */
    open class func getScenariosLaneRolesWithRequestBuilder(laneRole: String? = nil, heroId: Int? = nil) -> RequestBuilder<[ScenarioLaneRolesResponse]> {
        let localVariablePath = "/scenarios/laneRoles"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "lane_role": (wrappedValue: laneRole?.encodeToJSON(), isExplode: true),
            "hero_id": (wrappedValue: heroId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ScenarioLaneRolesResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     GET /scenarios/misc
     
     - parameter scenario: (query) Name of the scenario (see teamScenariosQueryParams) (optional)
     - returns: [ScenarioMiscResponse]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getScenariosMisc(scenario: String? = nil) async throws -> [ScenarioMiscResponse] {
        return try await getScenariosMiscWithRequestBuilder(scenario: scenario).execute().body
    }

    /**
     GET /scenarios/misc
     - GET /scenarios/misc
     - Miscellaneous team scenarios
     - parameter scenario: (query) Name of the scenario (see teamScenariosQueryParams) (optional)
     - returns: RequestBuilder<[ScenarioMiscResponse]> 
     */
    open class func getScenariosMiscWithRequestBuilder(scenario: String? = nil) -> RequestBuilder<[ScenarioMiscResponse]> {
        let localVariablePath = "/scenarios/misc"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "scenario": (wrappedValue: scenario?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ScenarioMiscResponse]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
