//
// DistributionsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DistributionsResponse: Codable, JSONEncodable, Hashable {

    public var ranks: DistributionsResponseRanks?

    public init(ranks: DistributionsResponseRanks? = nil) {
        self.ranks = ranks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ranks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ranks, forKey: .ranks)
    }
}

