//
// DistributionsResponseRanks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ranks */
public struct DistributionsResponseRanks: Codable, JSONEncodable, Hashable {

    /** rows */
    public var rows: [DistributionsResponseRanksRowsInner]?
    public var sum: DistributionsResponseRanksSum?

    public init(rows: [DistributionsResponseRanksRowsInner]? = nil, sum: DistributionsResponseRanksSum? = nil) {
        self.rows = rows
        self.sum = sum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rows
        case sum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rows, forKey: .rows)
        try container.encodeIfPresent(sum, forKey: .sum)
    }
}

