//
// DistributionsResponseRanksRowsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DistributionsResponseRanksRowsInner: Codable, JSONEncodable, Hashable {

    /** bin */
    public var bin: Int?
    /** bin_name */
    public var binName: Int?
    /** count */
    public var count: Int?
    /** cumulative_sum */
    public var cumulativeSum: Int?

    public init(bin: Int? = nil, binName: Int? = nil, count: Int? = nil, cumulativeSum: Int? = nil) {
        self.bin = bin
        self.binName = binName
        self.count = count
        self.cumulativeSum = cumulativeSum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bin
        case binName = "bin_name"
        case count
        case cumulativeSum = "cumulative_sum"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bin, forKey: .bin)
        try container.encodeIfPresent(binName, forKey: .binName)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(cumulativeSum, forKey: .cumulativeSum)
    }
}

