//
// HeroMatchupsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HeroMatchupsResponse: Codable, JSONEncodable, Hashable {

    /** The ID value of the hero played */
    public var heroId: Int?
    /** Number of games played */
    public var gamesPlayed: Int?
    /** Number of games won */
    public var wins: Int?

    public init(heroId: Int? = nil, gamesPlayed: Int? = nil, wins: Int? = nil) {
        self.heroId = heroId
        self.gamesPlayed = gamesPlayed
        self.wins = wins
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case heroId = "hero_id"
        case gamesPlayed = "games_played"
        case wins
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(heroId, forKey: .heroId)
        try container.encodeIfPresent(gamesPlayed, forKey: .gamesPlayed)
        try container.encodeIfPresent(wins, forKey: .wins)
    }
}

