//
// HeroItemPopularityResponseEarlyGameItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Items bought in the first 10 min of the game, with cost at least 700 */
public struct HeroItemPopularityResponseEarlyGameItems: Codable, JSONEncodable, Hashable {

    /** Number of item bought */
    public var item: Int?

    public init(item: Int? = nil) {
        self.item = item
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case item
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(item, forKey: .item)
    }
}

