//
// LeagueObjectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LeagueObjectResponse: Codable, JSONEncodable, Hashable {

    /** leagueid */
    public var leagueid: Int?
    /** ticket */
    public var ticket: String?
    /** banner */
    public var banner: String?
    /** tier */
    public var tier: String?
    /** League name */
    public var name: String?

    public init(leagueid: Int? = nil, ticket: String? = nil, banner: String? = nil, tier: String? = nil, name: String? = nil) {
        self.leagueid = leagueid
        self.ticket = ticket
        self.banner = banner
        self.tier = tier
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case leagueid
        case ticket
        case banner
        case tier
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(leagueid, forKey: .leagueid)
        try container.encodeIfPresent(ticket, forKey: .ticket)
        try container.encodeIfPresent(banner, forKey: .banner)
        try container.encodeIfPresent(tier, forKey: .tier)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

