//
// PlayerTotalsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayerTotalsResponse: Codable, JSONEncodable, Hashable {

    /** field */
    public var field: String?
    /** number */
    public var n: Int?
    /** sum */
    public var sum: Double?

    public init(field: String? = nil, n: Int? = nil, sum: Double? = nil) {
        self.field = field
        self.n = n
        self.sum = sum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case n
        case sum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(field, forKey: .field)
        try container.encodeIfPresent(n, forKey: .n)
        try container.encodeIfPresent(sum, forKey: .sum)
    }
}

