//
// PlayerWinLossResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayerWinLossResponse: Codable, JSONEncodable, Hashable {

    /** Number of wins */
    public var win: Int?
    /** Number of loses */
    public var lose: Int?

    public init(win: Int? = nil, lose: Int? = nil) {
        self.win = win
        self.lose = lose
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case win
        case lose
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(win, forKey: .win)
        try container.encodeIfPresent(lose, forKey: .lose)
    }
}

