//
// PlayerRankingsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayerRankingsResponse: Codable, JSONEncodable, Hashable {

    /** The ID value of the hero played */
    public var heroId: Int?
    /** Hero score */
    public var score: Double?
    /** percent_rank */
    public var percentRank: Double?
    /** numeric_rank */
    public var card: Int?

    public init(heroId: Int? = nil, score: Double? = nil, percentRank: Double? = nil, card: Int? = nil) {
        self.heroId = heroId
        self.score = score
        self.percentRank = percentRank
        self.card = card
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case heroId = "hero_id"
        case score
        case percentRank = "percent_rank"
        case card
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(heroId, forKey: .heroId)
        try container.encodeIfPresent(score, forKey: .score)
        try container.encodeIfPresent(percentRank, forKey: .percentRank)
        try container.encodeIfPresent(card, forKey: .card)
    }
}

