//
// PlayerObjectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayerObjectResponse: Codable, JSONEncodable, Hashable {

    /** The player account ID */
    public var accountId: Int?
    /** Player's steam identifier */
    public var steamid: String?
    /** Steam picture URL (small picture) */
    public var avatar: String?
    /** Steam picture URL (medium picture) */
    public var avatarmedium: String?
    /** Steam picture URL (full picture) */
    public var avatarfull: String?
    /** Steam profile URL */
    public var profileurl: String?
    /** Player's Steam name */
    public var personaname: String?
    /** Date and time of last login to OpenDota */
    public var lastLogin: Date?
    /** Date and time of last request to refresh player's match history */
    public var fullHistoryTime: Date?
    /** Amount of dollars the player has donated to OpenDota */
    public var cheese: Int?
    /** Whether the refresh of player' match history failed */
    public var fhUnavailable: Bool?
    /** Player's country identifier, e.g. US */
    public var loccountrycode: String?
    /** Verified player name, e.g. 'Miracle-' */
    public var name: String?
    /** Player's country code */
    public var countryCode: String?
    /** Player's ingame role (core: 1 or support: 2) */
    public var fantasyRole: Int?
    /** Player's team identifier */
    public var teamId: Int?
    /** Team name */
    public var teamName: String?
    /** Player's team shorthand tag, e.g. 'EG' */
    public var teamTag: String?
    /** Whether the roster lock is active */
    public var isLocked: Bool?
    /** Whether the player is professional or not */
    public var isPro: Bool?
    /** When the roster lock will end */
    public var lockedUntil: Int?

    public init(accountId: Int? = nil, steamid: String? = nil, avatar: String? = nil, avatarmedium: String? = nil, avatarfull: String? = nil, profileurl: String? = nil, personaname: String? = nil, lastLogin: Date? = nil, fullHistoryTime: Date? = nil, cheese: Int? = nil, fhUnavailable: Bool? = nil, loccountrycode: String? = nil, name: String? = nil, countryCode: String? = nil, fantasyRole: Int? = nil, teamId: Int? = nil, teamName: String? = nil, teamTag: String? = nil, isLocked: Bool? = nil, isPro: Bool? = nil, lockedUntil: Int? = nil) {
        self.accountId = accountId
        self.steamid = steamid
        self.avatar = avatar
        self.avatarmedium = avatarmedium
        self.avatarfull = avatarfull
        self.profileurl = profileurl
        self.personaname = personaname
        self.lastLogin = lastLogin
        self.fullHistoryTime = fullHistoryTime
        self.cheese = cheese
        self.fhUnavailable = fhUnavailable
        self.loccountrycode = loccountrycode
        self.name = name
        self.countryCode = countryCode
        self.fantasyRole = fantasyRole
        self.teamId = teamId
        self.teamName = teamName
        self.teamTag = teamTag
        self.isLocked = isLocked
        self.isPro = isPro
        self.lockedUntil = lockedUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case steamid
        case avatar
        case avatarmedium
        case avatarfull
        case profileurl
        case personaname
        case lastLogin = "last_login"
        case fullHistoryTime = "full_history_time"
        case cheese
        case fhUnavailable = "fh_unavailable"
        case loccountrycode
        case name
        case countryCode = "country_code"
        case fantasyRole = "fantasy_role"
        case teamId = "team_id"
        case teamName = "team_name"
        case teamTag = "team_tag"
        case isLocked = "is_locked"
        case isPro = "is_pro"
        case lockedUntil = "locked_until"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(steamid, forKey: .steamid)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(avatarmedium, forKey: .avatarmedium)
        try container.encodeIfPresent(avatarfull, forKey: .avatarfull)
        try container.encodeIfPresent(profileurl, forKey: .profileurl)
        try container.encodeIfPresent(personaname, forKey: .personaname)
        try container.encodeIfPresent(lastLogin, forKey: .lastLogin)
        try container.encodeIfPresent(fullHistoryTime, forKey: .fullHistoryTime)
        try container.encodeIfPresent(cheese, forKey: .cheese)
        try container.encodeIfPresent(fhUnavailable, forKey: .fhUnavailable)
        try container.encodeIfPresent(loccountrycode, forKey: .loccountrycode)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
        try container.encodeIfPresent(fantasyRole, forKey: .fantasyRole)
        try container.encodeIfPresent(teamId, forKey: .teamId)
        try container.encodeIfPresent(teamName, forKey: .teamName)
        try container.encodeIfPresent(teamTag, forKey: .teamTag)
        try container.encodeIfPresent(isLocked, forKey: .isLocked)
        try container.encodeIfPresent(isPro, forKey: .isPro)
        try container.encodeIfPresent(lockedUntil, forKey: .lockedUntil)
    }
}

