//
// PlayersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlayersResponse: Codable, JSONEncodable, Hashable {

    /** solo_competitive_rank */
    public var soloCompetitiveRank: Int?
    /** competitive_rank */
    public var competitiveRank: Int?
    /** rank_tier */
    public var rankTier: Double?
    /** leaderboard_rank */
    public var leaderboardRank: Double?
    public var profile: PlayersResponseProfile?

    public init(soloCompetitiveRank: Int? = nil, competitiveRank: Int? = nil, rankTier: Double? = nil, leaderboardRank: Double? = nil, profile: PlayersResponseProfile? = nil) {
        self.soloCompetitiveRank = soloCompetitiveRank
        self.competitiveRank = competitiveRank
        self.rankTier = rankTier
        self.leaderboardRank = leaderboardRank
        self.profile = profile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case soloCompetitiveRank = "solo_competitive_rank"
        case competitiveRank = "competitive_rank"
        case rankTier = "rank_tier"
        case leaderboardRank = "leaderboard_rank"
        case profile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(soloCompetitiveRank, forKey: .soloCompetitiveRank)
        try container.encodeIfPresent(competitiveRank, forKey: .competitiveRank)
        try container.encodeIfPresent(rankTier, forKey: .rankTier)
        try container.encodeIfPresent(leaderboardRank, forKey: .leaderboardRank)
        try container.encodeIfPresent(profile, forKey: .profile)
    }
}

